import Head from "next/head";
import Details from "../components/Details";
import Cart from "../components/Cart";

import { SimpleGrid } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Details Cart App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Components */}
      <SimpleGrid columns={{ base: 1, lg: 2 }} spacing={10}>
        <Details />
        <Cart />
      </SimpleGrid>
    </>
  );
}
